//@baseUrl = http://localhost:3333
@baseUrl = https://api.felipevaldez.com.br
@authToken = {{login.response.body.token.token}}

# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "felipe@teste.com",
  "password": "123456"
}

###

# @name ListarPlanoDeAulas
GET {{baseUrl}}/class-plan
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name CriarPlanoDeAulas
POST {{baseUrl}}/class-plan
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "group": "GROUP_02",
  "date": "2026-02-07T19:00:11.000Z",
  "subject": "Teoria Musical",
  "page": "1",
  "exercise": "Exercício 1",
  "classNumber": 1,
  "semester": "S1",
  "ano": 2026,
  "method": "teórica"
}

###

# @name AtualizarPlanoDeAulas
PUT {{baseUrl}}/class-plan/860dd6a2-afa6-40e4-9f03-8959bf34a9b4
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "group": "GROUP_01",
  "date": "2025-02-10T19:00:11.000Z",
  "subject": "Teoria Musical",
  "page": "12",
  "exercise": "Exercício 3"
}
