version: '3.8'

services:
  postgres:
    container_name: musicoson-pg
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=musicoson
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: musicoson-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - JWT_SECRET=musicosonseguro
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/musicoson?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Script para aguardar o banco e executar migrations
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/index.js
      "

volumes:
  postgres_data: