backend:
    # ... (outras configurações)
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Simplificado: A migração já foi feita no deploy.sh
    command: >
      sh -c "
        while ! nc -z postgres 5432; do
          echo 'Waiting for PostgreSQL...';
          sleep 2;
        done;
        # REMOVEMOS: npx prisma migrate deploy &&
        node dist/index.js
      "