version: '3.8'

services:
  postgres:
    container_name: musicoson-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=musicoson

  backend:
    container_name: musicoson-api
    build: .
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=production
      - PORT=3333
      - JWT_SECRET=musicosonseguro
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/musicoson?schema=public
    depends_on:
      - postgres
