name: Deploy Backend to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build (opcional)
        run: |
          docker build -t musicoson-api-test .

      # Deploy na VPS
      - name: Execute deploy.sh via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/musicoson-api
            # Solução para o erro de sobrescrita (git pull)
            git reset --hard
            git clean -fd
            git pull origin main
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh